function [ lf, param ] = LFRead( filename )
%LFREAD Read LF generated by LFSimPR

[pathstr, fname, ext] = fileparts(filename);
if ~strcmp(ext,'.json') && ~strcmp(ext,'.png')
    error('ERROR: Input file must be json or png files.');
end

param = LFReadMetadata(fullfile(pathstr,[fname '.json']));
sz = param.camParam.resol;
if strcmp(param.type, 'array-sa')
    lf = zeros([sz 3]);
    for i = 1:sz(1)
        for j = 1:sz(2)
            im = im2double(imread(fullfile(pathstr,fname,sprintf('Sub_%02d_%02d.png', i, j))));
            lf(i,j,:,:,:) = im(:,:,1:3);
        end
    end
else
    im = im2double(imread(fullfile(pathstr,[fname '.png'])));
    lf = raw2LF(im, sz);
end

end

